name: FoliaProxyWeaver
version: 1.0.0
main: com.example.foliaproxyweaver.FoliaProxyWeaverPlugin
api-version: 1.20
folia-supported: true
author: YourName
description: Restores client IPs when using frp/HAProxy by parsing the PROXY protocol via ProtoWeaver.
depend: [ProtoWeaver]